from lista_docs import LinkedList
import json
class Consultas:
    def __init__(self):
        data = LinkedList()
    
    def eq(self):
        ...
    def ne(self):
        ...  
    def gt(self):
        ... 
    def gte(self):
        ...
    def lt(self):
        ...
    def lte(self):
        ...

    def load(self, nombre_archivo: str):
        ...
    def find(self, buscar: dict):
        ...
    

